name: FUJI
manual_seed: 3407 # is all you need
output: runs

loss:
  types:
  - L1
  weights:
  - 1.0

data:
  name: SIDFujiDataset
  data_dir: /data/dataset/Carlos/SID/Fuji
  num_workers: 8
  pin_memory: true
  argument:
    transpose: true
    h_flip: true
    v_flip: true
  train:
    batch_size: 1
    image_list_file: train_00.txt
    patch_size: 512
  test:
    batch_size: 1
    image_list_file: test_00.txt

model:
  name: PGRawFormer
  PGRawFormer:
    in_channels: 9
    out_channels: 9
    dim: 32
    layers: 4
    num_meta_keys: 4
    num_blocks: [2,2,2,2]
    heads: [1,2,4,8]

train:
  base_lr: 2.0e-4
  last_lr_epoch: 500
  clip_grad: 0.1
  epochs: 500
  lr_scheduler:
    type: cosine
  optimizer: 
    type: adamw
    eps: 1.0e-8
    betas: [0.9, 0.999]
  min_lr: 1.0e-5
  start_epoch: 0
  weight_decay: 0
  warmup_epochs: 0

test:
  merge_test: true
  num_patch: 2 #null, -1, 2, 4
  patch_size: null

