name: SONY
manual_seed: 3407 # is all you need
output: runs

loss:
  types:
  - L1
  weights:
  - 1.0


data:
  name: SIDSonyDataset
  data_dir: /root/autodl-tmp/datasets/SID/Sony/
  num_workers: 16
  pin_memory: true
  argument:
    transpose: true
    h_flip: true
    v_flip: true
  train:
    batch_size: 1
    image_list_file: train_00.txt #280
    patch_size: 512
  test:
    batch_size: 1
    image_list_file: test_00.txt #129
    

model:
  name: DRANet
  DRANet:
    in_nc: 4
    out_nc: 4
    nc: 128
  MambaIR:
    inp_channels: 4
    out_channels: 4
    dim: 32
    num_blocks: [1, 1, 1, 1]
  
train:
  base_lr: 1.0e-4
  last_lr_epoch: 300
  clip_grad: 0.1
  epochs: 300
  lr_scheduler:
    type: cosine
  optimizer: 
    type: adamw
    eps: 1.0e-8
    betas: [0.9, 0.999]
  min_lr: 1.0e-5
  start_epoch: 0
  weight_decay: 0
  warmup_epochs: 0

test:
  merge_test: true
  num_patch: 2 #null, -1, 2, 4
  patch_size: null